import { Rubik } from 'next/font/google'
import Sidenav from '@/components/Sidenav'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { SidebarProvider } from '@/context/SidebarContext/SidebarProvider'
import { getServerUserDetails } from '../api/auth/actions/auth'

const rubik = Rubik({
    weight: ['300', '400', '500', '600', '700'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
})
export const metadata = {
    title: 'Bidsforce',
    description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
    let userRec = await getServerUserDetails()

    return (
        <div className='flex'>
            <SidebarProvider>
            <Sidenav userRec={userRec}/> 
            
                <div className='w-full'>
                    <Navbar />
                    <div className='p-7 bg-[#F2F4F6] min-h-[100vh]'  >
                        {children}
                    </div>
                    <Footer />
                </div>
            </SidebarProvider>
        </div >
    )
}
